# Generated by Django 3.1.7 on 2021-02-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='date',
        ),
    ]
